### PR TITLE
simplify container usage

### LINKED ISSUE #30: apply to Docker consistency guideline
When running in a Jenkins environment the following issue is raised:

```log
ERROR: The container started but didn't run the expected command. Please double check your ENTRYPOINT does execute the command passed as docker run argument, as required by official docker images (see https://github.com/docker-library/official-images#consistency for entrypoint consistency requirements).
Alternatively you can force image entrypoint to be disabled by adding option `--entrypoint=''`.
```

Jenkins pipeline:
```groovy
node {
  docker.image('sonarsource/sonar-scanner-cli').inside{
    sh "sonar-scanner --version"
  }
}
```

see https://github.com/docker-library/official-images#consistency

### PR DESCRIPTION
**Pull request by CCFenner**
- modifies `entrypoint` to allow calls like `docker run sonarsource/sonar-scanner-cli bash` and `docker run sonarsource/sonar-scanner-cli --version` or usage in Jenkins as described in #30  

copied from [nodejs/docker-node](https://github.com/nodejs/docker-node/blob/master/12/stretch/docker-entrypoint.sh)

fixes #30

### CODE REVIEW

**Comment by CCFenner** [comment]
@pierre-guillot-sonarsource @michal-duda-sonarsource any update on this? Would be nice to have this change in production to finally use the official Docker image.

**Comment by CCFenner** [comment]
❓ @pierre-guillot-sonarsource @michal-duda-sonarsource any update?

**Comment by michal-duda-sonarsource** [comment]
@CCFenner current plan is to look at this and some other improvements ([MMF-2003](https://jira.sonarsource.com/browse/MMF-2003)) after the release of SonarQube 8.3 (which should happen next week).

File: 4/bin/entrypoint.sh [hunk 1]
```diff
@@ -21,5 +21,9 @@ if [ "${SONAR_PROJECT_BASE_DIR:-}" ]; then
 fi
 
 export SONAR_USER_HOME="$PROJECT_BASE_DIR/.sonar"
-sonar-scanner "${args[@]}"
 
+if [ "${1#-}" != "${1}" ] || [ -z "$(command -v "${1}")" ]; then
+  set -- sonar-scanner "${args[@]}"
```
Comment (andreincx) [inline 4/bin/entrypoint.sh:26]: Would be nice to have the possibility to pass parameters directly, like -Dsonar.projectVersion=foo, which is not possible right now. Adding $* to the end of command would allow that. It also makes possible to overwrite any setting coming from environment variables since last parameters have precedence.
`  set -- sonar-scanner "${args[@]}" $*`
